<a href="https://colab.research.google.com/github/rashidkisejjere0784/depression-chatbot/blob/main/Depression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pyyaml

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
file = open("depression.yml", "r")

In [3]:
import yaml

In [4]:
text = yaml.load(file, Loader = yaml.FullLoader)

In [5]:
for item, doc in text.items():
  print(item, doc)

categories ['depression']
conversations [['What Is Depression?', 'Depression is a common and serious medical illness that negatively affects how you feel, the way you think and how you act.', 'Fortunately,it is also treatable.', 'Depression causes feelings of sadness and/or a loss of interest in activities you once enjoyed. It can lead to a variety of emotional and physical problems and can decrease your ability to function at work and at home.'], ['I feel i have let my parents down', 'No matter what,your parents will always be proud of you and will love you.', 'You will feel much better if you share your feelings with them.'], ['What are the types of depression?', 'There are many different forms of depression but most common types are.', 'Clinical depression,persistent depressive disorder,bipolar disorder,postnatal disorder.'], ['I am good for nothing.', "Don't ever think you cannot achieve what you want.", 'You are capable of reaching your goals.Here is a quote for you Everything you

In [6]:
data = text["conversations"]

In [7]:
import tensorflow as tf

In [8]:
tokenizer = tf.keras.preprocessing.text.Tokenizer(filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n',
lower=True,
split=" ",
char_level=False,
oov_token=None,
document_count=0)


In [62]:
Xtrain = []
ytrain = []

for row in data:
  Xtrain.append(row[0])
  ytrain.append(", " .join(row[1:]))

In [11]:
ytrain[10]

'This number represented 7.1% of all U.S. adults. The\xa0prevalence\xa0of major\xa0depressive\xa0episode was higher among adult females (8.7%) compared to males (5.3%). The\xa0prevalence\xa0of adults\xa0with\xa0a major\xa0depressive\xa0episode was\xa0highest\xa0among individuals aged 18-25 (13.1%).'

In [ ]:
Xtrain

['What Is Depression?',
 'I feel i have let my parents down',
 'What are the types of depression?',
 'I am good for nothing.',
 'I am feeling stressed lately',
 'i want to kill myself',
 'i am afraid i will fail again',
 'What is Depression?',
 'What are the causes of depression?',
 'What are the top causes of depression?',
 'Which age group has the highest rate of depression?',
 'Which country has the highest rate of depression?',
 'Which country has the lowest rate of depression?',
 'Is school a cause of depression?',
 'What is the biological cause of depression?',
 'How does depression affect the world?',
 'Which race has the highest rate of depression?',
 'What is the meaning of anxiety and depression?',
 'Does oversleeping cause depression?',
 'Can lack of sleep make you feel sad?',
 'Is depression a side effect of diabetes?',
 'Can low blood sugar cause suicidal thoughts?',
 'How long can Anxiety last?',
 'What are the stages of anxiety?',
 'At what age does anxiety peak?',
 'Why

In [12]:
tokenizer.fit_on_texts(Xtrain)

In [ ]:
tokenizer.document_count

51

In [ ]:
classes = len(ytrain)

In [13]:
import nltk

In [14]:
from nltk.stem import WordNetLemmatizer

In [15]:
lemmatizer = WordNetLemmatizer()

In [16]:
X = []

In [17]:
nltk.download('omw-1.4')
nltk.download("wordnet")

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

In [18]:
import re

exp = '[!\"#$%&\'()*+,-./:;<=>?@^_`{|}~]'

In [19]:
X = []
for sentence in Xtrain:
  words = sentence.split()
  row = []
  for word in words:
    word = re.sub(exp, "", word)
    row.append(lemmatizer.lemmatize(word))

  X.append(row)

In [ ]:
X

[['What', 'Is', 'Depression'],
 ['I', 'feel', 'i', 'have', 'let', 'my', 'parent', 'down'],
 ['What', 'are', 'the', 'type', 'of', 'depression'],
 ['I', 'am', 'good', 'for', 'nothing'],
 ['I', 'am', 'feeling', 'stressed', 'lately'],
 ['i', 'want', 'to', 'kill', 'myself'],
 ['i', 'am', 'afraid', 'i', 'will', 'fail', 'again'],
 ['What', 'is', 'Depression'],
 ['What', 'are', 'the', 'cause', 'of', 'depression'],
 ['What', 'are', 'the', 'top', 'cause', 'of', 'depression'],
 ['Which', 'age', 'group', 'ha', 'the', 'highest', 'rate', 'of', 'depression'],
 ['Which', 'country', 'ha', 'the', 'highest', 'rate', 'of', 'depression'],
 ['Which', 'country', 'ha', 'the', 'lowest', 'rate', 'of', 'depression'],
 ['Is', 'school', 'a', 'cause', 'of', 'depression'],
 ['What', 'is', 'the', 'biological', 'cause', 'of', 'depression'],
 ['How', 'doe', 'depression', 'affect', 'the', 'world'],
 ['Which', 'race', 'ha', 'the', 'highest', 'rate', 'of', 'depression'],
 ['What', 'is', 'the', 'meaning', 'of', 'anxiety', 

In [20]:
model = tf.keras.models.load_model("depression.h5")

In [ ]:
import numpy as np

In [57]:
ytrain = np.zeros((len(Xtrain), len(Xtrain)))

In [ ]:
ytrain.shape

(51, 51)

In [58]:
for i in range(0,len(Xtrain),1):
  ytrain[i,i] = 1

In [ ]:
ytrain[6]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
tokenizer.fit_on_texts(X)

In [22]:
tokenizer.word_docs

defaultdict(int,
            {'what': 20,
             'is': 16,
             'depression': 30,
             'down': 4,
             'let': 4,
             'feel': 4,
             'i': 48,
             'my': 6,
             'parents': 1,
             'have': 4,
             'the': 26,
             'are': 8,
             'of': 28,
             'types': 1,
             'am': 22,
             'good': 4,
             'for': 8,
             'nothing': 4,
             'stressed': 4,
             'lately': 4,
             'feeling': 4,
             'to': 8,
             'want': 6,
             'kill': 2,
             'myself': 4,
             'will': 4,
             'again': 2,
             'afraid': 4,
             'fail': 2,
             'causes': 2,
             'top': 2,
             'has': 5,
             'age': 4,
             'rate': 8,
             'group': 2,
             'highest': 6,
             'which': 8,
             'country': 4,
             'lowest': 2,
             'cause':

In [50]:
encoded_docs = tokenizer.texts_to_matrix(X)

encoded_docs

array([[0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]])

In [ ]:
encoded_docs.shape

(51, 137)

In [52]:
keras = tf.keras

In [53]:
model = keras.models.Sequential()

In [54]:
model.add(keras.layers.Dense(128, input_shape = (encoded_docs[0].shape)))
model.add(keras.layers.Dense(512, activation = "relu"))
model.add(keras.layers.BatchNormalization())
model.add(keras.layers.Dense(512, activation = "relu"))
model.add(keras.layers.Dense(128, activation = "relu"))
model.add(keras.layers.Dropout(0.25))
model.add(keras.layers.Dense(51, activation = "softmax"))

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               17664     
                                                                 
 dense_1 (Dense)             (None, 512)               66048     
                                                                 
 batch_normalization (BatchN  (None, 512)              2048      
 ormalization)                                                   
                                                                 
 dense_2 (Dense)             (None, 512)               262656    
                                                                 
 dense_3 (Dense)             (None, 128)               65664     
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                        

In [55]:
model.compile(optimizer = "sgd", loss = "categorical_crossentropy", metrics = ["accuracy"])

In [59]:
model.fit(encoded_docs, ytrain, epochs = 50, shuffle = True)

Epoch 1/50
2/2 [==============================] - 1s 12ms/step - loss: 4.1023 - accuracy: 0.0196
Epoch 2/50
2/2 [==============================] - 0s 12ms/step - loss: 3.7853 - accuracy: 0.0784
Epoch 3/50
2/2 [==============================] - 0s 13ms/step - loss: 3.6118 - accuracy: 0.0980
Epoch 4/50
2/2 [==============================] - 0s 12ms/step - loss: 3.4233 - accuracy: 0.1176
Epoch 5/50
2/2 [==============================] - 0s 12ms/step - loss: 3.3130 - accuracy: 0.1961
Epoch 6/50
2/2 [==============================] - 0s 17ms/step - loss: 3.0487 - accuracy: 0.3529
Epoch 7/50
2/2 [==============================] - 0s 11ms/step - loss: 2.9233 - accuracy: 0.3922
Epoch 8/50
2/2 [==============================] - 0s 12ms/step - loss: 2.7111 - accuracy: 0.4902
Epoch 9/50
2/2 [==============================] - 0s 11ms/step - loss: 2.5932 - accuracy: 0.5686
Epoch 10/50
2/2 [==============================] - 0s 13ms/step - loss: 2.4825 - accuracy: 0.5098
Epoch 11/50
2/2 [============

In [ ]:
sample = encoded_docs[6].reshape(1,137)
sample.shape

(1, 137)

In [ ]:
output = model.predict(sample)

1/1 [==============================] - 0s 25ms/step


In [ ]:
np.argmax(output[0])

6

In [ ]:
output[0].index

In [60]:
model.save("depression2.h5")

In [25]:
def Clean(text):
  tokens = text.split()
  cleaned = []
  for token in tokens:
    word = re.sub(exp, "", token)
    cleaned.append(lemmatizer.lemmatize(word))

  return cleaned


In [35]:
output = [Clean("i want to die")]

In [36]:
transformed = tokenizer.texts_to_matrix(output, mode = "count")

In [37]:
transformed.shape

(1, 137)

In [38]:
transformed

array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [43]:
import numpy as np

In [44]:
def predict(text):
  cleaned_text = Clean(text)
  text = [cleaned_text]
  encoded = tokenizer.texts_to_matrix(text, mode = "count")
  encoded = encoded.reshape((1, 137))
  prediction = model.predict(encoded)
  pred_class = np.argmax(prediction[0])
  return ytrain[pred_class]

In [70]:
predict(" what is depression")

1/1 [==============================] - 0s 21ms/step


'Depression\xa0is a mood disorder that causes a persistent feeling of sadness and loss of interest. Also called major\xa0depressive\xa0disorder or clinical\xa0depression, it affects how you feel, think and behave and can lead to a variety of emotional and physical problems.'

In [66]:
Xtrain

['What Is Depression?',
 'I feel i have let my parents down',
 'What are the types of depression?',
 'I am good for nothing.',
 'I am feeling stressed lately',
 'i want to kill myself',
 'i am afraid i will fail again',
 'What is Depression?',
 'What are the causes of depression?',
 'What are the top causes of depression?',
 'Which age group has the highest rate of depression?',
 'Which country has the highest rate of depression?',
 'Which country has the lowest rate of depression?',
 'Is school a cause of depression?',
 'What is the biological cause of depression?',
 'How does depression affect the world?',
 'Which race has the highest rate of depression?',
 'What is the meaning of anxiety and depression?',
 'Does oversleeping cause depression?',
 'Can lack of sleep make you feel sad?',
 'Is depression a side effect of diabetes?',
 'Can low blood sugar cause suicidal thoughts?',
 'How long can Anxiety last?',
 'What are the stages of anxiety?',
 'At what age does anxiety peak?',
 'Why